resources:
  jobs:
    Workflow_DAB:
      name: Workflow_DAB
      job_clusters:
       - job_cluster_key: "single-node-cluster"
         new_cluster:
          spark_version: "15.4.X-scala2.12"
          node_type_id: "m5a.large" 
          driver_node_type_id: "m5a.large"
          num_workers: 0
          spark_conf:
            "spark.databricks.cluster.profile": "singleNode"
            "spark.master": "local[*]"
          enable_elastic_disk: true
          custom_tags:
            ResourceClass: "SingleNode"
      tasks:
        - task_key: "JOBDAB_task"
          job_cluster_key: "single-node-cluster"
          notebook_task:
           notebook_path: /Workspace/Shared/dab_notebook
           source: WORK
