name: Deploy to Production

on:
  push:
    branches:
      - main  # Only trigger on pushes to main branch (after PR merge)

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production  # Fixed production environment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history

      - name: Verify merge commit
        run: |
          # Check if this is a merge commit (has two parent commits)
          if [ "$(git show -s --format=%p HEAD | wc -w)" -ne 2 ]; then
            echo "::error::Deployments only allowed after PR merges"
            exit 1
          fi
      - name: Install Databricks CLI
        run: |
              pip install databricks-cli --upgrade
              echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
              echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV
      - name: Configure Databricks CLI
        env:
            DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
            # Clean host URL (remove trailing slash)
            CLEAN_HOST="${DATABRICKS_HOST%/}"
    
            # Configure CLI using proper argument syntax
              databricks configure --token --host "$CLEAN_HOST" 

      - name: Validate bundle
        run: databricks bundle validate

      - name: Deploy to Production
        run: databricks bundle deploy -t prod

      - name: Verify deployment
        run: databricks bundle resources -t prod
